-- MySQL Script generated by MySQL Workbench
-- Sat May 26 09:28:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`twit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`twit` (
  `id_twit` INT NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(1000) NOT NULL,
  `fecha_twit` DATE NOT NULL,
  `localizacion` VARCHAR(45) NULL,
  `palabra_vlave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_twit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Analisis` (
  `id_Analisis` INT NOT NULL AUTO_INCREMENT,
  `texto_tweet` VARCHAR(45) NOT NULL,
  `Procentaje_Favorabilidad` VARCHAR(45) NOT NULL,
  `Sentimiento` VARCHAR(45) NOT NULL,
  `twit_id_twit` INT NOT NULL,
  PRIMARY KEY (`id_Analisis`),
  INDEX `fk_Analisis_twit_idx` (`twit_id_twit` ASC),
  CONSTRAINT `fk_Analisis_twit`
    FOREIGN KEY (`twit_id_twit`)
    REFERENCES `mydb`.`twit` (`id_twit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
